### ISSUE TITLE
Wildcard imports are broken instead of ignored

### ISSUE THREAD

**Issue by otaviomad** [Dschungelabenteuer/vite-plugin-entry-shaking#29]
**Describe the bug** A clear and concise description of what the bug is.

Importing `* as x` from any entry module breaks, since it will trigger the "load" function which will return a file with no exports.

**To Reproduce** Steps to reproduce the behavior:

1. Setup an entry file
2. Import `* as x` from that file
3. Log `x`, should be an empty module

**Expected behavior** A clear and concise description of what you expected to happen.

Wildcard imports should be properly ignored

**Comment by Dschungelabenteuer** [comment]
Thanks for reporting, this should be fixed in v0.3.3!  Please feel free to re-open, in case the latest release did not fix your issue :)
