### ISSUE TITLE
[Bug]: Invalidly generated Vue SFC code

### ISSUE THREAD

**Issue by fdc-viktor-luft** [Dschungelabenteuer/vite-plugin-entry-shaking#43]
### What does the bug relate to?

- [X] Plugin's core
- [ ] Debugger

### Describe the bug

The error message I'm receiving when running the code in Dev mode is:

```raw
Uncaught SyntaxError: Unexpected reserved word
```

Inspecting the code it looks like:

```ts
import _export_sfc from "/<private>/@id/__x00__plugin-vue:export-helper";
export default /* @__PURE__ */ _export_sfc(_sfc_main, [["render", _sfc_render], ["__scopeId", "data-v-4ccda690"], ["__file", "<private>/LocationSelectorPage.vue"]]);

export { default };
```

With the previous version the generated code looks like:

```
import _export_sfc from "/<private>/@id/__x00__plugin-vue:export-helper";
export default /* @__PURE__ */
_export_sfc(_sfc_main, [["render", _sfc_render], ["__scopeId", "data-v-4ccda690"], ["__file", "<private>/LocationSelectorPage.vue"]]);
```

Notice the `export { default };` in the end, which is also incorrect JS syntax.

### To Reproduce

- Set up a Vue-Vite project
- Render a component from an SFC module that is being re-exported by index file that is targeted by the vite-plugin-entry-shaking plugin

### Vite version

5.2.7

### Additional context

Tried vite-plugin-entry-shaking@0.4.0 and vite-plugin-entry-shaking@0.4.1 -> Same results.

**Comment by Dschungelabenteuer** [comment]
My bad, this got me off guard! v0.4.2 should fix that ;)

**Comment by fdc-viktor-luft** [comment]
Indeed, your update fixed it. Thank you 🎉
