### ISSUE TITLE
[Bug]: the default options of extensions does not match the documentation

### ISSUE THREAD

**Issue by Shunjun** [Dschungelabenteuer/vite-plugin-entry-shaking#50]
### What does the bug relate to?

- [X] Plugin's core
- [ ] Debugger

### Describe the bug

extensions in documentation is ['js', 'jsx', 'mjs', 'ts', 'tsx', 'mts']
but infact the default option is ['js', 'mjs', 'ts', 'mts']

### To Reproduce

-

### Vite version

5.2.7

**Comment by Dschungelabenteuer** [comment]
Damn, sorry about the unneeded confusion here. I'll either update the documentation to remove both unrelevant `(t|j)sx` extensions due to es-module-lexer's limitations, or track your #49 issue then actually add both extensions to the default ones as stated in the documentation. I'll let you know.
